
// -----------------------
//         Users
// -----------------------

GET http://localhost:3000/user/all
###


POST http://localhost:3000/user/register
Content-Type:application/json

{
	"username":  "Icaruk",
	"email":  "asd@asd.com",
	"password":  "1234",
	"phone":  "600123456",
	"address":	"c/ ASD"
}
###


POST http://localhost:3000/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###


GET http://localhost:3000/user/logout/5dcd7652394fde1938a80f02
###


GET http://localhost:3000/user/5dcd7652394fde1938a80f02
###


DELETE http://localhost:3000/user/delete/5dcd7652394fde1938a80f02
###



// -----------------------
//         Movies
// -----------------------



GET http://localhost:3000/movie/id/458897
###


GET http://localhost:3000/movie/title/Madre
###


GET http://localhost:3000/movie/genre/28
###


GET http://localhost:3000/movie/popular/3
###


GET http://localhost:3000/movie/newest/100
###


GET http://localhost:3000/movie/oldest/100
###


POST http://localhost:3000/movie/add
Content-Type:application/json

{
	"id": 1,
	"title": "Titulo", 
	"original_title": "Titulo original",
	"release_date": "2019-11-13",
	"runtime": 60,
	"overview": "resumen",
	"poster_path": "link poster",
	"backdrop_path": "link back",
	"video": false,
	"genre_ids": [1, 2, 3],
	"adult": false,
	"original_language": "ES",
	"popularity": 40,
	"vote_count": 50,
	"vote_average": 60
}
###


DELETE http://localhost:3000/movie/delete/1
###



// -----------------------
//         Orders
// -----------------------

POST http://localhost:3000/order/add
Content-Type:application/json

{
	"movieId": 458897,
	"clientId": "5dcd7652394fde1938a80f02",
	"startDate": [2019, 11, 15, 14, 24],
	"endDate": [2019, 11, 16, 14, 24],
	"city": "Valencia"
}
###


GET http://localhost:3000/order/5dcecb8dd831db2590cd01a8
###


// order/complete/{id order}${status}
GET http://localhost:3000/order/setStatus/5dcecb8dd831db2590cd01a8&0
###
GET http://localhost:3000/order/setStatus/5dcecb8dd831db2590cd01a8&1
###
GET http://localhost:3000/order/setStatus/5dcecb8dd831db2590cd01a8&2
###


DELETE http://localhost:3000/order/delete/5dcec9994f5222428c8186d5
###










// -----------------------
//         ???
// -----------------------


PATCH http://localhost:3000/user/5dcbf2dc0329af4f646903a1
Content-Type:application/json

{
   "username":"Juanjo"
}
###


DELETE http://localhost:3000/user/5dcbfd594ce1014194f2f64e
