
// Register
POST http://localhost:3000/user/register
Content-Type:application/json

{
	"username":  "Icaruk3",
	"email": "asd3@asd.com",
	"password":  "1234",
	"phone": "647123456",
	"address": "c/ Falsa, 123",
	"billing": {
		"cardNumber": 123456789,
		"cardOwner": "Adrian Apellido Apellido",
		"cardExpireDate": [6, 22]
	}
}
###


// Login
# @name resLogin
POST http://localhost:3000/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###


@userId = {{resLogin.response.body.userId}}
@token = {{resLogin.response.body.token}}


// Logout
GET http://localhost:3000/user/logout?token={{token}}
###


// Ver datos del usuario
GET http://localhost:3000/user/{{userId}}?token={{token}}
###


// Ver las pelis top10 populares (sin token)
GET http://localhost:3000/movie/popular?limit=10
###

// Ver las pelis top50 populares
GET http://localhost:3000/movie/popular?limit=10&token={{token}}
###


// Ver las pelis top10 nuevas
GET http://localhost:3000/movie/newest?limit=10&token={{token}}
###


// Ver las pelis top20 viejas
GET http://localhost:3000/movie/oldest?limit=10&token={{token}}
###


// Buscar una peli que contenga "madre" en el título
GET http://localhost:3000/movie/search?limit=10&title=madre&token={{token}}
###


// Buscar una peli con la id 337154
GET http://localhost:3000/movie/search?id=337154&token={{token}}
###


// Buscar pelis con el género 12
GET http://localhost:3000/movie/search?limit=10&genre=12&token={{token}}
###


// Ver todas las pelis (cuidao que son 10k)
GET http://localhost:3000/movie/all?limit=10&token={{token}}
###


// Crea un pedido
POST http://localhost:3000/order/add?token={{token}}
Content-Type:application/json

{
	"movieId": 458897,
	"userId": {{userId}},
	"city": "Valencia"
}
###


// Ver datos del pedido
GET http://localhost:3000/order/{{userId}}?token={{token}}
###


// Ver los pedidos de un cliente
GET http://localhost:3000/order/client/{{userId}}?token={{token}}
###


// Marcar como finalizado
GET http://localhost:3000/order/setStatus/{{userId}}?status=1&token={{token}}
###


// Borra el pedido
DELETE http://localhost:3000/order/delete/{{userId}}?token={{token}}
###


// Delete user
DELETE http://localhost:3000/user/delete/{{userId}}?token={{token}}
###

