
// Login
POST http://localhost:3000/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###


// Ver datos del usuario
GET http://localhost:3000/user/5dcd7652394fde1938a80f02?token=5dd0446a727c8f4e2816e993
###


// Ver las pelis top50 populares
GET http://localhost:3000/movie/popular/50?token=5dd0446a727c8f4e2816e993
###


// Ver las pelis top10 nuevas
GET http://localhost:3000/movie/newest/10?token=5dd0446a727c8f4e2816e993
###


// Ver las pelis top20 viejas
GET http://localhost:3000/movie/oldest/20?token=5dd0446a727c8f4e2816e993
###


// Buscar una peli que contenga "madre" en el título
GET http://localhost:3000/movie/search?title=madre&token=5dd0446a727c8f4e2816e993
###


// Buscar una peli con la id 337154
GET http://localhost:3000/movie/search?id=337154&token=5dd0446a727c8f4e2816e993
###


// Buscar una peli con el género 12
GET http://localhost:3000/movie/search?genre=12&token=5dd0446a727c8f4e2816e993
###


// Ver todas las pelis (cuidao que son 10k)
GET http://localhost:3000/movie/all?token=5dd0446a727c8f4e2816e993
###


// Crea un pedido
POST http://localhost:3000/order/add?token=5dd0446a727c8f4e2816e993
Content-Type:application/json

{
	"movieId": 458897,
	"clientId": "5dcd7652394fde1938a80f02",
	"city": "Valencia"
}
###


// Ver datos del pedido
GET http://localhost:3000/order/5dd0479b03b820227c4361b0?token=5dd0446a727c8f4e2816e993
###


// Ver los pedidos de un cliente
GET http://localhost:3000/order/client/5dcd7652394fde1938a80f02?token=5dd0446a727c8f4e2816e993
###


// Marcar como finalizado
GET http://localhost:3000/order/setStatus/5dd0479b03b820227c4361b0?status=1&token=5dd0446a727c8f4e2816e993
###


// Borra el pedido
DELETE http://localhost:3000/order/delete/5dd0479b03b820227c4361b0?token=5dd0446a727c8f4e2816e993
###


// Logout
GET http://localhost:3000/user/logout?token=5dd0446a727c8f4e2816e993
###

